[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[[services]]
name = "vpbank-chatbot"
healthcheckPath = "/health"
healthcheckTimeout = 100
autoDeploy = true 

[deploy]
startCommand = "./start.sh"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
RUNTIME_ENVIRONMENT = "production"
GOOGLE_CLOUD_PROJECT = "communi-ai"
DATABASE_URL = "${{ Postgres.DATABASE_URL }}"